### ISSUE TITLE
Consider using globalpy

### ISSUE THREAD

**Issue by frankzl** [aadhithya/tum_console#3]
Hey have you considered using the package global-py?

if you install global-py, you can just run "globalpy -t tum_console.py -a tum_console"

and then you can enjoy tum_console from anywhere :)

**Comment by aadhithya** [comment]
Is this an issue or an advertisement for your script!!? 😆 yes yes, I’ll once you make it available on PyPI! 👍🏼

**Comment by aadhithya** [comment]
Done.
